### ISSUE TITLE
The Google Analytics Snippet is included in the wrong place

### ISSUE THREAD

**Issue by grantkemp** [googlecodelabs/performance-analytics#1]
Under step 6 - the Google analytis Snippet is added at the bottom - this is not the place that Google recommends it - which is in the header just before the closing head tag. 

Which is the correct place to put the snippet? Whats the implication of putting it into the header on this exercise?

**Comment by philipwalton** [comment]
Google Analytics recommends putting the snippet in the `<head>` to two main reasons:
1. So the library loads as quickly as possible.
2. To reduce the likelihood of errors if you make `ga()` call in your templates.

However, if you know what you're doing and you're not putting `ga()` calls throughout your templates, you can safely put the script anywhere. It makes no difference.

The codelab suggests putting it last so it doesn't get prioritized over loading a script your app actually needs to function.
