### ISSUE TITLE
Section 8 (step 4) aync attribute effects

### ISSUE THREAD

**Issue by jmanuel1** [googlecodelabs/performance-analytics#2]
The section begins:

> Since `<script>` tags with the `async` attribute block DOM parsing until they've been both downloaded and executed, ...

Should this be "without the `async` attribute"?

**Comment by philipwalton** [comment]
Thanks! I've fixed the source doc. The fix should go live the next time the Code Labs site is built. 

@marcacohen is the site still being rebuilt periodically? If not can it be manually rebuilt to pick up this change?

**Comment by philipwalton** [comment]
This has been updated.
