### ISSUE TITLE
Section 9 (step 5) example output missing

### ISSUE THREAD

**Issue by jmanuel1** [googlecodelabs/performance-analytics#3]
The final image showing example output from the console is missing.

![image](https://cloud.githubusercontent.com/assets/7255867/15984761/5491ede4-3011-11e6-8ca8-e7eadeb71a22.png)

**Comment by philipwalton** [comment]
There isn't an image of the console output from this step because none of the output has changed from the previous step. The only thing that's changed is the code now works cross-browser.

**Comment by jmanuel1** [comment]
Maybe that last sentence should be removed then?

**Comment by philipwalton** [comment]
Ahh, yes, thank you. I missed that before. I'll update.
