### ISSUE TITLE
GA Tag goes after the opening <head...> tag

### ISSUE THREAD

**Issue by tomwhartung** [googlecodelabs/performance-analytics#5]
Near the beginning of section 10, Step 6 of the Measuring Critical Performance Metrics with Google Analytics code lab ( https://codelabs.developers.google.com/codelabs/performance-analytics/index.html?index=..%2F..%2Findex#9 ) it says:

"Add the following code to index.html after the main JavaScript block but before the perf-analytics.js script is loaded:"

This is saying to add the tag to the end of the file.

In the third part of the first lesson (1.3) in the Google Academy class, Google Analytics for Beginners, it says to add the tag after the opening <head...> tag ( https://analytics.google.com/analytics/academy/course/6/unit/1/lesson/3 ).

My guess is that the Google Academy Class is correct here, and the code lab is wrong.

Thanks.

**Comment by philipwalton** [comment]
Neither are wrong. You can add the script anywhere you want to your page. The only thing adding it earlier will do is ensure it gets loaded sooner. In some cases this is what you want, but in some cases it's not (i.e. you want to prioritize loading your site's JS more than loading GA).

FYI, here's some of my person thoughts on how best to configure GA for websites:
https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/
